#!/bin/bash

season=1
episode=1
series_name=$(dirname "$PWD")
series_name=${series_name##*/}

while [[ $# -gt 0 ]]; do
    case $1 in
	-n|--name)
	    series_name="$2"
	    shift # argument
	    shift # value
	    ;;
	-x|--extension)
	    extension="$2"
	    shift # argument
	    shift # value
	    ;;
	-s|--season)
	    season="$2"
	    shift # argument
	    shift # value
	    ;;
	-e|--episode)
	    episode="$2"
	    shift # argument
	    shift # value
	    ;;
	-d|--dryrun)
	    dryrun="TRUE"
	    shift # argument
	    ;;
	-q|--quiet)
	    quiet="TRUE"
	    shift # argument
	    ;;
	*)
	    echo "ERROR: Unknown option $1"
	    exit 1
	    ;;
    esac
done

if [ -n "$extension" ]; then
    extension=".$extension"
fi

integer='^[0-9]+$'
if ! [[ $season =~ $integer ]] ; then
   echo "ERROR: Season must be an integer number"
   exit 1
fi

if ! [[ $episode =~ $integer ]] ; then
   echo "ERROR: Episode must be an integer number"
   exit 1
fi

for file in *"$extension"; do
    name="$series_name S$(printf %02d "$season")E$(printf %02d "$episode")$extension"
    if [ "$quiet" != "TRUE" ]; then
        echo "$file --> $name"
    fi
    if [ "$dryrun" != "TRUE" ]; then
        mv "$file" "$name"
    fi
    episode=$((episode + 1))
done
